[package]
name = "exonum_leveldb"
version = "0.9.1"
authors = ["Florian Gilcher <florian.gilcher@asquera.de>", "The Exonum Team <exonum@bitfury.com>"]
description = "An interface for leveldb"
license = "MIT"
readme = "README.md"
repository = "https://github.com/exonum/exonum"

[lib]
name = "exonum_leveldb"

[dependencies]
libc = "0.2.26"
leveldb-sys="2.0.1"

[dev-dependencies]
tempdir = "0.3.5"

[[test]]
name = "tests"
