[package]
name = "propose_timeout_adjuster"
version = "0.1.0"
authors = ["Ivan Ivashchenko <ivan.ivashchenko@xdev.re",
           "Aleksey Sidorov <aleksei.sidorov@xdev.re>"]

[dependencies]
exonum = {version="0.1", path="../../exonum"}
blockchain_explorer = {version="0.1", path="../../blockchain_explorer"}

time = "0.1"
serde = "0.8"
serde_derive = "0.8"

clap = "2.14"
env_logger = "0.3"
log = "0.3"
