[workspace]

members = [
    "3rdparty/leveldb-sys",
    "3rdparty/leveldb",
    "3rdparty/flamer",
    "3rdparty/profiler",
    "blockchain_explorer",
    "cryptocurrency",
    "exonum",
    "sandbox",
    "services/configuration",
    "services/propose_timeout_adjuster",
]