[workspace]

members = [
    "3rdparty/leveldb-sys",
    "3rdparty/leveldb",
<<<<<<< HEAD
    "blockchain_explorer",
=======
    "blockchain_explorer",    
>>>>>>> CI fix
    "exonum",
    "sandbox",
    "services/configuration",
    "services/propose_timeout_adjuster",
]