[workspace]

members = [
    "3rdparty/leveldb-sys",
    "3rdparty/leveldb",
    "blockchain_explorer",
    "cryptocurrency",
    "digital_rights",
    "exonum",
    "sandbox",
    "timestamping",
    "land_title"
]