[package]
name = "exonum"
version = "0.1.0"
authors = ["Bitfury Inc. <ivan.ivashchenko@xdev.re>"]

[dependencies]
log = "0.3"
mio = "0.5"
time = "0.1"
byteorder = "0.5"
hex = "0.2"
num = "0.1"
bit-vec = "0.4"
vec_map = "0.6.0"
sodiumoxide = {git = "https://github.com/dnaq/sodiumoxide.git", rev="0c9f41f"}
rand = "0.3"
leveldb = {version="0.9", path="../3rdparty/leveldb"}
serde = "0.8"
serde_derive = "0.8"
valico = "1"
serde_json = "0.8"
toml = {version="0.2", default-features=false, features=["serde"]}
clippy = {version = "0.0.107", optional = true}

[dev-dependencies]
tempdir = "0.3"
env_logger = "0.3"

[features]
default = []
long_benchmarks = []
memorydb = []
sandbox_events = []
